name: serial_port
version: 0.4.0-dev
description: Dart extension library to communicate on serial port.
author: Nicolas Francois  <nicolas.franc@gmail.com>
homepage: https://github.com/nfrancois/serial_port
environnment:
  sdk: '>=1.13.0 <2.0.0'
dev_dependencies:
  grinder: ">=0.8.0 <0.9.0"
  ccompile: ">=0.2.10 <0.3.0"
  test: ">=0.12.7 <0.13.0"
  dart_coveralls: ">=0.4.0 <0.5.0"
  dartdoc: ">=0.8.5 <0.9.0"
