name: poweron
description: A web server for poweron project.
version: 0.0.1
#homepage: https://www.example.com
author: Michal Karas <mike.om4aa@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  shelf: ^0.6.0
  redstone: any

#dev_dependencies:
#  test: ^0.12.0
